version: '3'
services:
  server:
    build: .
    container_name: server
    depends_on:
      - db
      - cache
    ports:
      - 4000:4000
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis

  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    container_name: redis
    restart: always
    entrypoint: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data

volumes:
  postgres:
  redis:
