version: '3'
services:
  server:
    build: .
    container_name: toron-server
    depends_on:
      - db
    ports:
      - 4000:4000
    environment:
      POSTGRES_HOST: postgres

  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/toron

volumes:
  db-data:
